import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Popular from "../components/Popular";

export default function Home({movies}) {
      console.log(movies);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

<Popular movies={movies}/>

      </main>
    </>
  );
}

export async function getServerSideProps() {
  const request = await fetch(`https://api.themoviedb.org/3/movie/popular?api_key=3044afc915e1301ae1d9551614db3711&language=en-US&page=1`);
  const movies = await request.json();
  return {
    props: {
      movies
    }
  }
}

//? veri çekmenin 1. yolu
// export async function getStaticProps() {
//   const request = await fetch(`https://api.themoviedb.org/3/movie/popular?api_key=3044afc915e1301ae1d9551614db3711&language=en-US&page=1`);
//   const movies = await request.json();
//   return {
//     props: {
//       movies
//     }
//   }
// }
